on:
  push:
    branches: ['master']

env:
  NODE_VERSION: '20.x'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # Run tests with
      #   - Run in band because appears to run more smoothly (avoids memory issues when running in parallel?)
      #   - Fifteen (!) minute test timeout
      #   - Force exit to prevent hanging
      - name: Run tests
        run: npx jest --runInBand --testTimeout=900000 --forceExit
        env:
          # Tell Node.js how much un-garbage-collected-memory it can
          # allow for to prevent it running out (in Mb)
          NODE_OPTIONS: --max_old_space_size=14000

      - name: Release package
        if: github.ref == 'refs/heads/master'
        run: |
          set -e
          npm ci
          mkdir -p docs
          npx semantic-release
        env:
          GIT_AUTHOR_NAME: Stencila CI Bot
          GIT_AUTHOR_EMAIL: ci@stenci.la
          GIT_COMMITTER_NAME: Stencila CI Bot
          GIT_COMMITTER_EMAIL: ci@stenci.la
          GITHUB_TOKEN: $(GITHUB_TOKEN)
          NPM_TOKEN: $(NPM_TOKEN)
